### ISSUE TITLE
Switch to RSpec

### ISSUE THREAD

**Issue by jcamenisch** [brightbit/rails-template#16]
## Tasks
- [ ] Use RSpec successfully on one or two projects.
- [ ] Evaluate the difference in the experience.
- [ ] Roll the boilerplate setup into rails-template
